### ISSUE TITLE
hostname not set on CentOS 9

### ISSUE THREAD

**Issue by laurentgo** [GoogleCloudPlatform/guest-configs#47]
When using Google Centos Stream 9 image, the VM hostname remains `localhost` instead of the usual VM name or hostname configured.

Google package: `google-compute-engine-20221110.00-g1.el9.noarch`

When changing `NetworkManager` log level to trace (on a freshly created VM), observing the following messages:

```
Apr 11 23:29:59 localhost NetworkManager[674]: <debug> [1681255799.0247] policy: set-hostname: current hostname was changed outside NetworkManager: 'localhost'
Apr 11 23:29:59 localhost NetworkManager[674]: <trace> [1681255799.0247] policy: device hostname info:
Apr 11 23:29:59 localhost NetworkManager[674]: <trace> [1681255799.0247] policy:   - prio:  100 ipv4 (def) dhcp  dns  dev:eth0
Apr 11 23:29:59 localhost NetworkManager[674]: <trace> [1681255799.0247] policy:   - prio:  100 ipv6       dhcp  dns  dev:eth0
Apr 11 23:29:59 localhost NetworkManager[674]: <trace> [1681255799.0247] policy: get-hostname: "localhost" (from dbus)
Apr 11 23:29:59 localhost NetworkManager[674]: <info>  [1681255799.0247] policy: set-hostname: set hostname to 'test-vm-centos-9.c.my-project.internal' (from DHCPv4)
```

**Comment by zmarano** [comment]
We fixed this issue and it turned out to be an issue with static vs transient host names due to systemd changes. This [change in systemd](https://github.com/systemd/systemd/commit/d39079fcaa05e23540d2b1f0270fa31c22a7e9f1) caused a behavioral change where a static host name set to `localhost` in `/etc/hostname` would prevent the transient host name from being used from DHCP.  The reason `/etc/hostname` was set was because the [kickstart configs](https://github.com/GoogleCloudPlatform/compute-image-tools/pull/2125) we use for EL based images, it was being set. Removing that initial static host name fixes the issue.
